server:
  port: 8180

spring:
  profiles:    active: local  datasource:
    driver-class-name: org.mariadb.jdbc.Driver    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://127.0.0.1:3306/db_insung_lol?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 1013
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true  
# logging
logging:
  level:
    root: info
    org.hibernate.sql: debug
    
jwt:
  secret: jwtsecret
  jwtExpirationMs: 900000
  rjwtExpirationMs: 1800000